/**
 * Evolved allies — operatives summoned from fractured realms across the multiverse.
 */
const CROSSOVER_BARRACKS_COST = 90;
const CROSSOVER_BARRACKS_BUILDERS = 2;

const CrossoverFactions = {
  ultimis: {
    id: 'ultimis',
    label: 'Void Residue Crew',
    building: 'element_barracks',
    unlockKey: 'is115Unlocked',
  },
  primis: {
    id: 'primis',
    label: 'First Circle',
    building: 'primis_shrine',
    unlockKey: 'isPrimusUnlocked',
  },
  halo: {
    id: 'halo',
    label: 'Orbital Vanguard',
    building: 'spartan_academy',
    unlockKey: 'isHaloUnlocked',
  },
  gears: {
    id: 'gears',
    label: 'Iron Trench Coalition',
    building: 'cog_academy',
    unlockKey: 'isGearsUnlocked',
  },
  lotr: {
    id: 'lotr',
    label: 'Ninefold March',
    building: 'rivendell_camp',
    unlockKey: 'isLotrUnlocked',
  },
  baki: { id: 'baki', label: 'Iron Pit Guild', building: 'hanma_dojo', unlockKey: 'isBakiUnlocked' },
  jojo: {
    id: 'jojo',
    label: 'Bound Spirit Court',
    building: 'stand_arrow_shrine',
    unlockKey: 'isJojoUnlocked',
  },
  fotns: {
    id: 'fotns',
    label: 'North Star Ascetics',
    building: 'north_star_dojo',
    unlockKey: 'isFotnsUnlocked',
  },
  dragonball: {
    id: 'dragonball',
    label: 'Skyburst Order',
    building: 'capsule_corp',
    unlockKey: 'isDragonballUnlocked',
  },
  imperium: {
    id: 'imperium',
    label: 'Crimson Legions',
    building: 'astartes_chapel',
    unlockKey: 'isImperiumUnlocked',
  },
  crystal: {
    id: 'crystal',
    label: 'Crystal Vanguard',
    building: 'crystal_sanctum',
    unlockKey: 'isCrystalUnlocked',
  },
  warp: {
    id: 'warp',
    label: 'Rift Cult',
    building: 'warp_shrine',
    unlockKey: 'isWarpUnlocked',
  },
  tes: {
    id: 'tes',
    label: 'Voicebound Pact',
    building: 'dragon_moot',
    unlockKey: 'isTesUnlocked',
  },
};

const CrossoverDefs = {
  // Void Residue Crew
  tank_dempsey: {
    name: 'Splinter Vale',
    faction: 'ultimis',
    cost: 24,
    hp: 210,
    accuracy: 50,
    damage: 54,
    range: 28,
    meleeRange: 28,
    speed: 1.05,
    type: 'melee',
    morale: 28,
    experience: 12,
    ability: 'frag_out',
    abilityDesc: 'Grenade Burst — bonus damage vs clustered foes.',
    color: '#c06030',
    combatTag: 'melee',
  },
  richtofen: {
    name: 'Dr. Volkov',
    faction: 'ultimis',
    cost: 22,
    hp: 165,
    accuracy: 52,
    damage: 48,
    range: 160,
    meleeRange: 24,
    speed: 1.0,
    type: 'ranged',
    projectile: 'bolt',
    morale: 24,
    experience: 13,
    ability: 'wunderwaffe',
    abilityDesc: 'Mad genius — chain lightning on elite hits.',
    color: '#8040a0',
    combatTag: 'ranged',
  },
  nikolai: {
    name: 'Brass Kozlov',
    faction: 'ultimis',
    cost: 23,
    hp: 240,
    accuracy: 42,
    damage: 46,
    range: 28,
    meleeRange: 28,
    speed: 0.92,
    type: 'melee',
    morale: 30,
    experience: 11,
    ability: 'vodka_rage',
    abilityDesc: 'Iron Rage — damage reduction when wounded.',
    color: '#406080',
    combatTag: 'melee',
  },
  takeo: {
    name: 'Blade Sato',
    faction: 'ultimis',
    cost: 22,
    hp: 185,
    accuracy: 58,
    damage: 50,
    range: 26,
    meleeRange: 26,
    speed: 1.18,
    type: 'melee',
    morale: 26,
    experience: 14,
    ability: 'bushido',
    abilityDesc: 'Bushido — crit chance rises with stars earned.',
    color: '#308050',
    combatTag: 'melee',
  },

  // First Circle
  primis_tank: {
    name: 'Splinter Vale (Ascended)',
    faction: 'primis',
    cost: 25,
    hp: 240,
    accuracy: 54,
    damage: 58,
    range: 30,
    meleeRange: 30,
    speed: 1.08,
    type: 'melee',
    morale: 30,
    experience: 13,
    ability: 'apothicon_slam',
    abilityDesc: 'Void Slam — cleave on kill.',
    color: '#d07040',
    combatTag: 'melee',
  },
  primis_nikolai: {
    name: 'Brass Kozlov (Ascended)',
    faction: 'primis',
    cost: 25,
    hp: 270,
    accuracy: 46,
    damage: 52,
    range: 30,
    meleeRange: 30,
    speed: 0.95,
    type: 'melee',
    morale: 32,
    experience: 12,
    ability: 'iron_curtain',
    abilityDesc: 'Iron Curtain — brief invulnerability pulse below 35% HP.',
    color: '#5080a0',
    combatTag: 'melee',
  },
  primis_takeo: {
    name: 'Blade Sato (Ascended)',
    faction: 'primis',
    cost: 24,
    hp: 200,
    accuracy: 60,
    damage: 56,
    range: 28,
    meleeRange: 28,
    speed: 1.22,
    type: 'melee',
    morale: 28,
    experience: 15,
    ability: 'katana_fury',
    abilityDesc: 'Blade Fury — rapid strikes on wounded targets.',
    color: '#40a060',
    combatTag: 'melee',
  },
  primis_richtofen: {
    name: 'Dr. Volkov (Ascended)',
    faction: 'primis',
    cost: 23,
    hp: 175,
    accuracy: 55,
    damage: 52,
    range: 170,
    meleeRange: 24,
    speed: 1.02,
    type: 'ranged',
    projectile: 'bolt',
    morale: 26,
    experience: 14,
    ability: 'summoning_key',
    abilityDesc: 'Void Key — drains elite HP to heal allies.',
    color: '#9040c0',
    combatTag: 'support',
  },

  // Orbital Vanguard
  master_chief: {
    name: 'Sentinel-7',
    faction: 'halo',
    cost: 30,
    hp: 320,
    accuracy: 58,
    damage: 62,
    range: 180,
    meleeRange: 28,
    speed: 1.05,
    type: 'ranged',
    projectile: 'arrow',
    morale: 35,
    experience: 16,
    ability: 'spartan_rage',
    abilityDesc: 'Vanguard Rage — shields allies near him on wave start.',
    color: '#408040',
    combatTag: 'ranged',
  },
  noble_six: {
    name: 'Lance Operative',
    faction: 'halo',
    cost: 25,
    hp: 220,
    accuracy: 56,
    damage: 54,
    range: 175,
    meleeRange: 26,
    speed: 1.12,
    type: 'ranged',
    projectile: 'arrow',
    morale: 28,
    experience: 14,
    ability: 'lone_wolf',
    abilityDesc: 'Lone Wolf — bonus damage when isolated.',
    color: '#608060',
    combatTag: 'ranged',
  },
  sgt_johnson: {
    name: 'Sergeant Ashford',
    faction: 'halo',
    cost: 24,
    hp: 250,
    accuracy: 48,
    damage: 50,
    range: 30,
    meleeRange: 30,
    speed: 0.98,
    type: 'melee',
    morale: 38,
    experience: 12,
    ability: 'oorah',
    abilityDesc: 'Oorah! — rally pulse and morale on wave start.',
    color: '#a08040',
    combatTag: 'support',
  },
  noble_carter: {
    name: 'Wolf Leader',
    faction: 'halo',
    cost: 23,
    hp: 200,
    accuracy: 52,
    damage: 48,
    range: 160,
    meleeRange: 26,
    speed: 1.0,
    type: 'ranged',
    projectile: 'arrow',
    morale: 30,
    experience: 13,
    ability: 'noble_leader',
    abilityDesc: 'Wolf Leader — buffs nearby vanguard operatives.',
    color: '#506050',
    combatTag: 'support',
  },
  noble_kat: {
    name: 'Cat Operative',
    faction: 'halo',
    cost: 22,
    hp: 175,
    accuracy: 54,
    damage: 46,
    range: 165,
    meleeRange: 24,
    speed: 1.08,
    type: 'ranged',
    projectile: 'arrow',
    morale: 26,
    experience: 13,
    ability: 'tech_ops',
    abilityDesc: 'Tech Ops — debuffs enemy accuracy in aura.',
    color: '#6080a0',
    combatTag: 'support',
  },
  noble_emile: {
    name: 'Ember Operative',
    faction: 'halo',
    cost: 24,
    hp: 195,
    accuracy: 50,
    damage: 58,
    range: 28,
    meleeRange: 28,
    speed: 1.1,
    type: 'melee',
    morale: 22,
    experience: 12,
    ability: 'energy_sword',
    abilityDesc: 'Plasma Blade — devastating melee finishers.',
    color: '#804040',
    combatTag: 'melee',
  },
  noble_jorge: {
    name: 'Heavy Gunner',
    faction: 'halo',
    cost: 32,
    hp: 340,
    accuracy: 40,
    damage: 70,
    range: 140,
    meleeRange: 30,
    speed: 0.82,
    type: 'ranged',
    projectile: 'bolt',
    morale: 32,
    experience: 11,
    ability: 'grenadier',
    abilityDesc: 'Grenadier — splash damage on every third shot.',
    color: '#705030',
    combatTag: 'ranged',
  },
  noble_jun: {
    name: 'Sniper Operative',
    faction: 'halo',
    cost: 24,
    hp: 180,
    accuracy: 62,
    damage: 52,
    range: 220,
    meleeRange: 24,
    speed: 1.05,
    type: 'ranged',
    projectile: 'arrow',
    morale: 24,
    experience: 14,
    ability: 'sniper_cover',
    abilityDesc: 'Sniper Cover — extreme range, bonus vs elites.',
    color: '#507050',
    combatTag: 'ranged',
  },
  spartan_soldier: {
    name: 'Vanguard Trooper',
    faction: 'halo',
    cost: 22,
    hp: 180,
    accuracy: 50,
    damage: 42,
    range: 170,
    meleeRange: 24,
    speed: 1.05,
    type: 'ranged',
    projectile: 'arrow',
    morale: 22,
    experience: 10,
    ability: 'spartan_training',
    abilityDesc: 'Vanguard Training — steady ranged DPS.',
    color: '#508050',
    combatTag: 'ranged',
  },

  // Iron Trench Coalition
  marcus_fenix: {
    name: 'Marcus Ironhart',
    faction: 'gears',
    cost: 26,
    hp: 240,
    accuracy: 52,
    damage: 56,
    range: 150,
    meleeRange: 28,
    speed: 1.0,
    type: 'ranged',
    projectile: 'arrow',
    morale: 32,
    experience: 14,
    ability: 'lancer_burst',
    abilityDesc: 'Burst Lancer — chainsaw finisher on low HP foes.',
    color: '#506080',
    combatTag: 'ranged',
  },
  dom_santiago: {
    name: 'Dom Calder',
    faction: 'gears',
    cost: 24,
    hp: 210,
    accuracy: 48,
    damage: 48,
    range: 140,
    meleeRange: 26,
    speed: 1.02,
    type: 'ranged',
    projectile: 'arrow',
    morale: 34,
    experience: 12,
    ability: 'brothers_in_arms',
    abilityDesc: 'Brothers in Arms — heals Ironhart when nearby.',
    color: '#6080a0',
    combatTag: 'support',
  },
  damon_baird: {
    name: 'Damon Gearwright',
    faction: 'gears',
    cost: 22,
    hp: 175,
    accuracy: 54,
    damage: 44,
    range: 160,
    meleeRange: 24,
    speed: 1.05,
    type: 'ranged',
    projectile: 'arrow',
    morale: 24,
    experience: 13,
    ability: 'tech_head',
    abilityDesc: 'Tech Head — bonus damage vs siege and structures.',
    color: '#a0a040',
    combatTag: 'ranged',
  },
  augustus_cole: {
    name: 'Augustus Cole',
    faction: 'gears',
    cost: 26,
    hp: 260,
    accuracy: 44,
    damage: 58,
    range: 30,
    meleeRange: 30,
    speed: 0.95,
    type: 'melee',
    morale: 28,
    experience: 11,
    ability: 'cole_train',
    abilityDesc: 'Iron Charge — charges through enemy lines.',
    color: '#c04040',
    combatTag: 'melee',
  },
  anthony_carmine: {
    name: 'Anthony Ironhelm',
    faction: 'gears',
    cost: 20,
    hp: 150,
    accuracy: 46,
    damage: 40,
    range: 145,
    meleeRange: 24,
    speed: 1.0,
    type: 'ranged',
    projectile: 'arrow',
    morale: 20,
    experience: 9,
    ability: 'carmine_curse',
    abilityDesc: 'Ironhelm Curse — fragile, but cheap lancer support.',
    color: '#608040',
    combatTag: 'ranged',
  },
  clayton_carmine: {
    name: 'Clayton Ironhelm',
    faction: 'gears',
    cost: 28,
    hp: 280,
    accuracy: 42,
    damage: 62,
    range: 150,
    meleeRange: 28,
    speed: 0.88,
    type: 'ranged',
    projectile: 'bolt',
    morale: 30,
    experience: 11,
    ability: 'heavy_lancer',
    abilityDesc: 'Heavy Lancer — suppressive fire shreds groups.',
    color: '#708050',
    combatTag: 'ranged',
  },
  benjamin_carmine: {
    name: 'Benjamin Ironhelm',
    faction: 'gears',
    cost: 21,
    hp: 165,
    accuracy: 48,
    damage: 42,
    range: 145,
    meleeRange: 24,
    speed: 1.02,
    type: 'ranged',
    projectile: 'arrow',
    morale: 22,
    experience: 10,
    ability: 'carmine_brother',
    abilityDesc: 'Ironhelm Brother — buffs other Ironhelms nearby.',
    color: '#508060',
    combatTag: 'support',
  },
  cog_soldier: {
    name: 'Trench Trooper',
    faction: 'gears',
    cost: 20,
    hp: 170,
    accuracy: 46,
    damage: 38,
    range: 145,
    meleeRange: 24,
    speed: 0.98,
    type: 'ranged',
    projectile: 'arrow',
    morale: 20,
    experience: 9,
    ability: 'lancer_drill',
    abilityDesc: 'Lancer Drill — standard trench ranged line-holder.',
    color: '#506070',
    combatTag: 'ranged',
  },

  // Lord of the Rings
  aragorn: {
    name: 'Crownless Ranger',
    faction: 'lotr',
    cost: 26,
    hp: 250,
    accuracy: 54,
    damage: 58,
    range: 30,
    meleeRange: 30,
    speed: 1.05,
    type: 'melee',
    morale: 36,
    experience: 15,
    ability: 'anduril',
    abilityDesc: 'Crownblade — bonus damage vs elites and dark knights.',
    color: '#406050',
    combatTag: 'melee',
  },
  legolas: {
    name: 'Silvan Archer',
    faction: 'lotr',
    cost: 24,
    hp: 180,
    accuracy: 62,
    damage: 52,
    range: 220,
    meleeRange: 26,
    speed: 1.2,
    type: 'ranged',
    projectile: 'arrow',
    morale: 28,
    experience: 14,
    ability: 'elven_archer',
    abilityDesc: 'Elven Archer — extreme range, bonus vs fast foes.',
    color: '#508060',
    combatTag: 'ranged',
  },
  gimli: {
    name: 'Stone Axe Lord',
    faction: 'lotr',
    cost: 26,
    hp: 280,
    accuracy: 44,
    damage: 56,
    range: 26,
    meleeRange: 26,
    speed: 0.88,
    type: 'melee',
    morale: 32,
    experience: 12,
    ability: 'axe_cleave',
    abilityDesc: 'Axe Cleave — splash on siege targets.',
    color: '#806040',
    combatTag: 'melee',
  },
  gandalf: {
    name: 'Grey Pilgrim',
    faction: 'lotr',
    cost: 26,
    hp: 200,
    accuracy: 55,
    damage: 60,
    range: 180,
    meleeRange: 28,
    speed: 1.0,
    type: 'ranged',
    projectile: 'bolt',
    morale: 38,
    experience: 16,
    ability: 'you_shall_not_pass',
    abilityDesc: 'Grey Ward — terrifies nearby enemies.',
    color: '#c0c0e0',
    combatTag: 'support',
  },
  frodo: {
    name: 'Halfling Scout',
    faction: 'lotr',
    cost: 18,
    hp: 140,
    accuracy: 48,
    damage: 36,
    range: 24,
    meleeRange: 24,
    speed: 1.1,
    type: 'melee',
    morale: 30,
    experience: 12,
    ability: 'ring_bearer',
    abilityDesc: 'Scout Ring — evasion and morale aura for allies.',
    color: '#608040',
    combatTag: 'support',
  },
  boromir: {
    name: 'Shield Captain',
    faction: 'lotr',
    cost: 24,
    hp: 230,
    accuracy: 46,
    damage: 54,
    range: 28,
    meleeRange: 28,
    speed: 0.95,
    type: 'melee',
    morale: 34,
    experience: 13,
    ability: 'horn_of_gondor',
    abilityDesc: 'Shield Horn — rally pulse when surrounded.',
    color: '#704030',
    combatTag: 'melee',
  },
  eowyn: {
    name: 'Shield Maiden',
    faction: 'lotr',
    cost: 23,
    hp: 195,
    accuracy: 52,
    damage: 50,
    range: 28,
    meleeRange: 28,
    speed: 1.15,
    type: 'melee',
    morale: 30,
    experience: 14,
    ability: 'no_man',
    abilityDesc: 'I Am No Man — devastating finisher vs elite foes.',
    color: '#a08060',
    combatTag: 'melee',
  },

  // Iron Pit Guild
  baki_hanma: {
    name: 'Ironson Baki',
    faction: 'baki',
    cost: 24,
    hp: 210,
    accuracy: 56,
    damage: 58,
    range: 26,
    meleeRange: 26,
    speed: 1.18,
    type: 'melee',
    morale: 26,
    experience: 14,
    ability: 'demon_back',
    abilityDesc: 'Demon Back — damage spikes when below half HP.',
    color: '#c04040',
    combatTag: 'melee',
  },
  yujiro_hanma: {
    name: 'The Ogre Patriarch',
    faction: 'baki',
    cost: 33,
    hp: 380,
    accuracy: 58,
    damage: 78,
    range: 32,
    meleeRange: 32,
    speed: 1.1,
    type: 'melee',
    morale: 18,
    experience: 16,
    ability: 'ogre',
    abilityDesc: 'The Ogre — near-boss tier melee devastation.',
    color: '#802020',
    combatTag: 'melee',
  },
  doppo_orochi: {
    name: 'Doppo Serpent',
    faction: 'baki',
    cost: 23,
    hp: 200,
    accuracy: 54,
    damage: 52,
    range: 26,
    meleeRange: 26,
    speed: 1.08,
    type: 'melee',
    morale: 28,
    experience: 13,
    ability: 'goudou',
    abilityDesc: 'Goudou — precision strikes on wounded targets.',
    color: '#504060',
    combatTag: 'melee',
  },
  jack_hanma: {
    name: 'Jack Ironson',
    faction: 'baki',
    cost: 26,
    hp: 240,
    accuracy: 42,
    damage: 62,
    range: 30,
    meleeRange: 30,
    speed: 0.92,
    type: 'melee',
    morale: 20,
    experience: 12,
    ability: 'bite',
    abilityDesc: 'Bite — bonus damage vs larger enemies.',
    color: '#606060',
    combatTag: 'melee',
  },
  oliva_biscuit: {
    name: 'Oliva Biscuit',
    faction: 'baki',
    cost: 29,
    hp: 340,
    accuracy: 38,
    damage: 60,
    range: 28,
    meleeRange: 28,
    speed: 0.78,
    type: 'melee',
    morale: 24,
    experience: 11,
    ability: 'iron_body',
    abilityDesc: 'Iron Body — heavy damage reduction.',
    color: '#806050',
    combatTag: 'melee',
  },
  kaku_kaioh: {
    name: 'Kaku Kaioh',
    faction: 'baki',
    cost: 22,
    hp: 185,
    accuracy: 58,
    damage: 48,
    range: 26,
    meleeRange: 26,
    speed: 1.12,
    type: 'melee',
    morale: 30,
    experience: 14,
    ability: 'aiki',
    abilityDesc: 'Aiki — counters and punishes reckless attackers.',
    color: '#406080',
    combatTag: 'melee',
  },
  pickle: {
    name: 'The Primal',
    faction: 'baki',
    cost: 31,
    hp: 360,
    accuracy: 35,
    damage: 70,
    range: 30,
    meleeRange: 30,
    speed: 0.85,
    type: 'melee',
    morale: 12,
    experience: 10,
    ability: 'primitive_fury',
    abilityDesc: 'Primitive Fury — raw prehistoric power.',
    color: '#605040',
    combatTag: 'melee',
  },

  // Bound Spirit Court (Part 7 = cavalry)
  jonathan_joestar: {
    name: 'Jonathan Ashford',
    faction: 'jojo',
    cost: 23,
    hp: 220,
    accuracy: 48,
    damage: 50,
    range: 28,
    meleeRange: 28,
    speed: 1.0,
    type: 'melee',
    morale: 34,
    experience: 13,
    ability: 'hamon_overdrive',
    abilityDesc: 'Solar Pulse — bonus vs undead elites.',
    color: '#4060a0',
    combatTag: 'melee',
    jojoPart: 1,
  },
  dio_brando_p1: {
    name: 'Dio Crimson',
    faction: 'jojo',
    cost: 24,
    hp: 200,
    accuracy: 52,
    damage: 56,
    range: 28,
    meleeRange: 28,
    speed: 1.12,
    type: 'melee',
    morale: 22,
    experience: 14,
    ability: 'vaporization_freeze',
    abilityDesc: 'Crimson Chill — slows enemy morale.',
    color: '#c0c040',
    combatTag: 'melee',
    jojoPart: 1,
  },
  zeppeli: {
    name: 'Will Zephyr',
    faction: 'jojo',
    cost: 21,
    hp: 175,
    accuracy: 50,
    damage: 44,
    range: 26,
    meleeRange: 26,
    speed: 1.05,
    type: 'melee',
    morale: 32,
    experience: 14,
    ability: 'sunlight_yellow',
    abilityDesc: 'Solar Heal — heals allies on elite kill.',
    color: '#c0a040',
    combatTag: 'support',
    jojoPart: 1,
  },
  joseph_joestar_p2: {
    name: 'Joseph Ashford',
    faction: 'jojo',
    cost: 23,
    hp: 190,
    accuracy: 50,
    damage: 48,
    range: 160,
    meleeRange: 26,
    speed: 1.1,
    type: 'ranged',
    projectile: 'bolt',
    morale: 30,
    experience: 13,
    ability: 'hermit_purple',
    abilityDesc: 'Violet Snare — trick shots and scouting debuffs.',
    color: '#8040a0',
    combatTag: 'ranged',
    jojoPart: 2,
  },
  caesar_zeppeli: {
    name: 'Caesar Zephyr',
    faction: 'jojo',
    cost: 22,
    hp: 170,
    accuracy: 52,
    damage: 46,
    range: 150,
    meleeRange: 24,
    speed: 1.15,
    type: 'ranged',
    projectile: 'bolt',
    morale: 28,
    experience: 13,
    ability: 'bubble_cutter',
    abilityDesc: 'Pressure Cutter — crit from range.',
    color: '#40a0c0',
    combatTag: 'ranged',
    jojoPart: 2,
  },
  stroheim: {
    name: 'Rudol Ironclad',
    faction: 'jojo',
    cost: 25,
    hp: 240,
    accuracy: 44,
    damage: 52,
    range: 140,
    meleeRange: 26,
    speed: 0.9,
    type: 'ranged',
    projectile: 'arrow',
    morale: 26,
    experience: 11,
    ability: 'german_science',
    abilityDesc: 'Iron Science — bonus vs siege units.',
    color: '#808080',
    combatTag: 'ranged',
    jojoPart: 2,
  },
  jotaro_kujo: {
    name: 'Jotaro Ashen',
    faction: 'jojo',
    cost: 27,
    hp: 260,
    accuracy: 56,
    damage: 62,
    range: 30,
    meleeRange: 30,
    speed: 1.05,
    type: 'melee',
    morale: 28,
    experience: 15,
    ability: 'star_platinum',
    abilityDesc: 'Spirit Rush — spirit rush on pinned foes.',
    color: '#404080',
    combatTag: 'melee',
    jojoPart: 3,
  },
  kakyoin: {
    name: 'Noriaki Emerald',
    faction: 'jojo',
    cost: 22,
    hp: 165,
    accuracy: 54,
    damage: 48,
    range: 170,
    meleeRange: 24,
    speed: 1.0,
    type: 'ranged',
    projectile: 'bolt',
    morale: 26,
    experience: 13,
    ability: 'hierophant_green',
    abilityDesc: 'Emerald Spray — emerald splash AoE.',
    color: '#40c040',
    combatTag: 'ranged',
    jojoPart: 3,
  },
  polnareff: {
    name: 'Jean Pierre Silver',
    faction: 'jojo',
    cost: 23,
    hp: 195,
    accuracy: 52,
    damage: 54,
    range: 28,
    meleeRange: 28,
    speed: 1.18,
    type: 'melee',
    morale: 28,
    experience: 13,
    ability: 'silver_chariot',
    abilityDesc: 'Silver Flurry — flurry attacks on low HP foes.',
    color: '#c0c0c0',
    combatTag: 'melee',
    jojoPart: 3,
  },
  avdol: {
    name: 'Mohammed Flame',
    faction: 'jojo',
    cost: 24,
    hp: 180,
    accuracy: 50,
    damage: 52,
    range: 160,
    meleeRange: 26,
    speed: 1.0,
    type: 'ranged',
    projectile: 'bolt',
    morale: 30,
    experience: 13,
    ability: 'magicians_red',
    abilityDesc: "Crimson Flame — fire splash on hit.",
    color: '#c04020',
    combatTag: 'support',
    jojoPart: 3,
  },
  josuke_higashikata: {
    name: 'Josuke Diamond',
    faction: 'jojo',
    cost: 23,
    hp: 210,
    accuracy: 48,
    damage: 52,
    range: 28,
    meleeRange: 28,
    speed: 1.02,
    type: 'melee',
    morale: 32,
    experience: 13,
    ability: 'crazy_diamond',
    abilityDesc: 'Restorative March — heals allies he passes.',
    color: '#8040a0',
    combatTag: 'support',
    jojoPart: 4,
  },
  okuyasu: {
    name: 'Okuyasu Hand',
    faction: 'jojo',
    cost: 25,
    hp: 220,
    accuracy: 40,
    damage: 58,
    range: 30,
    meleeRange: 30,
    speed: 0.95,
    type: 'melee',
    morale: 24,
    experience: 11,
    ability: 'the_hand',
    abilityDesc: 'The Hand — erases space, bonus single-target burst.',
    color: '#6040a0',
    combatTag: 'melee',
    jojoPart: 4,
  },
  rohan_kishibe: {
    name: 'Rohan Artist',
    faction: 'jojo',
    cost: 22,
    hp: 160,
    accuracy: 58,
    damage: 46,
    range: 175,
    meleeRange: 24,
    speed: 1.05,
    type: 'ranged',
    projectile: 'arrow',
    morale: 22,
    experience: 14,
    ability: 'heavens_door',
    abilityDesc: 'Script Ward — debuffs enemy accuracy.',
    color: '#e0e0c0',
    combatTag: 'ranged',
    jojoPart: 4,
  },
  kira_yoshikage: {
    name: 'Yoshikage Quiet',
    faction: 'jojo',
    cost: 23,
    hp: 185,
    accuracy: 54,
    damage: 56,
    range: 26,
    meleeRange: 26,
    speed: 1.0,
    type: 'melee',
    morale: 20,
    experience: 14,
    ability: 'killer_queen',
    abilityDesc: 'Quiet Erase — final toll on wounded foes.',
    color: '#a040c0',
    combatTag: 'melee',
    jojoPart: 4,
  },
  giorno_giovanna: {
    name: 'Giorno Gold',
    faction: 'jojo',
    cost: 23,
    hp: 200,
    accuracy: 52,
    damage: 54,
    range: 28,
    meleeRange: 28,
    speed: 1.08,
    type: 'melee',
    morale: 34,
    experience: 15,
    ability: 'gold_experience',
    abilityDesc: 'Golden Pulse — heals allies on kill.',
    color: '#e0c040',
    combatTag: 'support',
    jojoPart: 5,
  },
  bruno_bucciarati: {
    name: 'Bruno Zipper',
    faction: 'jojo',
    cost: 23,
    hp: 205,
    accuracy: 52,
    damage: 52,
    range: 28,
    meleeRange: 28,
    speed: 1.1,
    type: 'melee',
    morale: 36,
    experience: 14,
    ability: 'sticky_fingers',
    abilityDesc: 'Zip Fingers — zip-line reposition and rally.',
    color: '#4060c0',
    combatTag: 'melee',
    jojoPart: 5,
  },
  guido_mista: {
    name: 'Guido Pistols',
    faction: 'jojo',
    cost: 23,
    hp: 175,
    accuracy: 55,
    damage: 50,
    range: 165,
    meleeRange: 24,
    speed: 1.05,
    type: 'ranged',
    projectile: 'arrow',
    morale: 26,
    experience: 13,
    ability: 'sex_pistols',
    abilityDesc: 'Ricochet Pistols — ricochet shots hit multiple foes.',
    color: '#4080c0',
    combatTag: 'ranged',
    jojoPart: 5,
  },
  diavolo: {
    name: 'Crimson King',
    faction: 'jojo',
    cost: 25,
    hp: 220,
    accuracy: 50,
    damage: 60,
    range: 28,
    meleeRange: 28,
    speed: 1.12,
    type: 'melee',
    morale: 18,
    experience: 15,
    ability: 'king_crimson',
    abilityDesc: 'Crimson Erase — deletes wounded targets.',
    color: '#802060',
    combatTag: 'melee',
    jojoPart: 5,
  },
  jolyne_cujoh: {
    name: 'Jolyne String',
    faction: 'jojo',
    cost: 23,
    hp: 195,
    accuracy: 52,
    damage: 50,
    range: 26,
    meleeRange: 26,
    speed: 1.15,
    type: 'melee',
    morale: 30,
    experience: 14,
    ability: 'stone_free',
    abilityDesc: 'Stone Free — string traps slow enemies.',
    color: '#40a080',
    combatTag: 'melee',
    jojoPart: 6,
  },
  weather_report: {
    name: 'Storm Caller',
    faction: 'jojo',
    cost: 24,
    hp: 180,
    accuracy: 54,
    damage: 56,
    range: 170,
    meleeRange: 24,
    speed: 1.0,
    type: 'ranged',
    projectile: 'bolt',
    morale: 26,
    experience: 14,
    ability: 'weather_stand',
    abilityDesc: 'Weather Stand — AoE lightning pressure.',
    color: '#80c0e0',
    combatTag: 'ranged',
    jojoPart: 6,
  },
  ermes_costello: {
    name: 'Ermes Kiss',
    faction: 'jojo',
    cost: 21,
    hp: 170,
    accuracy: 50,
    damage: 46,
    range: 26,
    meleeRange: 26,
    speed: 1.1,
    type: 'melee',
    morale: 28,
    experience: 13,
    ability: 'kiss',
    abilityDesc: 'Kiss — duplicates pressure on elite kills.',
    color: '#c04080',
    combatTag: 'melee',
    jojoPart: 6,
  },
  johnny_joestar: {
    name: 'Johnny Rotation',
    faction: 'jojo',
    cost: 23,
    hp: 175,
    accuracy: 52,
    damage: 54,
    range: 32,
    meleeRange: 32,
    speed: 1.45,
    type: 'cavalry',
    morale: 28,
    experience: 15,
    canHunt: true,
    ability: 'tusk_act4',
    abilityDesc: 'Rotation ACT4 — infinite rotation charge finisher.',
    color: '#c0a060',
    combatTag: 'melee',
    jojoPart: 7,
  },
  gyro_zeppeli: {
    name: 'Gyro Ballista',
    faction: 'jojo',
    cost: 23,
    hp: 185,
    accuracy: 55,
    damage: 52,
    range: 30,
    meleeRange: 30,
    speed: 1.4,
    type: 'cavalry',
    morale: 32,
    experience: 14,
    canHunt: true,
    ability: 'steel_ball',
    abilityDesc: 'Steel Ball — golden spin cleave on charge.',
    color: '#c08040',
    combatTag: 'ranged',
    jojoPart: 7,
  },
  diego_brando: {
    name: 'Diego Brando',
    faction: 'jojo',
    cost: 24,
    hp: 190,
    accuracy: 54,
    damage: 58,
    range: 32,
    meleeRange: 32,
    speed: 1.5,
    type: 'cavalry',
    morale: 22,
    experience: 14,
    canHunt: true,
    ability: 'scary_monsters',
    abilityDesc: 'Predator Form — predatory charge damage.',
    color: '#608040',
    combatTag: 'melee',
    jojoPart: 7,
  },
  lucy_steel: {
    name: 'Lucy Ticket',
    faction: 'jojo',
    cost: 19,
    hp: 155,
    accuracy: 48,
    damage: 40,
    range: 30,
    meleeRange: 30,
    speed: 1.35,
    type: 'cavalry',
    morale: 34,
    experience: 13,
    canHunt: true,
    ability: 'ticket_to_ride',
    abilityDesc: 'Ticket to Ride — support cavalry rally aura.',
    color: '#c0a0a0',
    combatTag: 'support',
    jojoPart: 7,
  },

  // North Star Ascetics
  kenshiro: {
    name: 'Ken Northstar',
    faction: 'fotns',
    cost: 29,
    hp: 280,
    accuracy: 58,
    damage: 68,
    range: 28,
    meleeRange: 28,
    speed: 1.05,
    type: 'melee',
    morale: 32,
    experience: 16,
    ability: 'hidan_shinken',
    abilityDesc: 'North Star Fist — rapid finisher on low HP foes.',
    color: '#c0c0e0',
    combatTag: 'melee',
  },
  raoh: {
    name: 'Raoh Ken-Oh',
    faction: 'fotns',
    cost: 31,
    hp: 350,
    accuracy: 50,
    damage: 72,
    range: 32,
    meleeRange: 32,
    speed: 0.9,
    type: 'melee',
    morale: 28,
    experience: 15,
    ability: 'hokuto_kaioh',
    abilityDesc: 'Ken-Oh — terror aura and siege bonus.',
    color: '#404040',
    combatTag: 'melee',
  },
  toki: {
    name: 'Toki Healer',
    faction: 'fotns',
    cost: 22,
    hp: 190,
    accuracy: 52,
    damage: 48,
    range: 26,
    meleeRange: 26,
    speed: 1.0,
    type: 'melee',
    morale: 36,
    experience: 14,
    ability: 'hakke_shou',
    abilityDesc: 'Hakke Shou — heals allies in aura.',
    color: '#e0e0f0',
    combatTag: 'support',
  },
  rei: {
    name: 'Rei Suicho',
    faction: 'fotns',
    cost: 22,
    hp: 175,
    accuracy: 54,
    damage: 52,
    range: 28,
    meleeRange: 28,
    speed: 1.2,
    type: 'melee',
    morale: 26,
    experience: 13,
    ability: 'nanto_suicho',
    abilityDesc: 'Nanto Suichō Ken — fast strikes on multiple foes.',
    color: '#4080c0',
    combatTag: 'melee',
  },
  jaggi: {
    name: 'Jagi Traitor',
    faction: 'fotns',
    cost: 23,
    hp: 200,
    accuracy: 42,
    damage: 50,
    range: 28,
    meleeRange: 28,
    speed: 0.95,
    type: 'melee',
    morale: 16,
    experience: 11,
    ability: 'dirty_tricks',
    abilityDesc: 'Dirty Tricks — debuffs enemy morale on hit.',
    color: '#605050',
    combatTag: 'melee',
  },
  shin: {
    name: 'Shin Scar',
    faction: 'fotns',
    cost: 24,
    hp: 210,
    accuracy: 46,
    damage: 54,
    range: 30,
    meleeRange: 30,
    speed: 1.0,
    type: 'melee',
    morale: 22,
    experience: 12,
    ability: 'nanto_hakuro',
    abilityDesc: 'Nanto Hakuro Ken — heavy single-target blows.',
    color: '#806080',
    combatTag: 'melee',
  },

  // Skyburst Order
  goku: {
    name: 'Kael Skyburst',
    faction: 'dragonball',
    cost: 28,
    hp: 280,
    accuracy: 52,
    damage: 64,
    range: 30,
    meleeRange: 30,
    speed: 1.12,
    type: 'melee',
    morale: 32,
    experience: 15,
    ability: 'kamehameha',
    abilityDesc: 'Skyburst Wave — burst finisher when surrounded.',
    color: '#e06040',
    combatTag: 'ki',
  },
  vegeta: {
    name: 'Prince Vex',
    faction: 'dragonball',
    cost: 27,
    hp: 270,
    accuracy: 54,
    damage: 62,
    range: 30,
    meleeRange: 30,
    speed: 1.1,
    type: 'melee',
    morale: 28,
    experience: 15,
    ability: 'galick_gun',
    abilityDesc: 'Prince Beam — bonus vs elites, pride damage boost.',
    color: '#4060c0',
    combatTag: 'ki',
  },
  piccolo: {
    name: 'Namek Sage',
    faction: 'dragonball',
    cost: 25,
    hp: 220,
    accuracy: 50,
    damage: 54,
    range: 165,
    meleeRange: 26,
    speed: 1.0,
    type: 'ranged',
    projectile: 'bolt',
    morale: 30,
    experience: 14,
    ability: 'special_beam',
    abilityDesc: 'Piercing Beam — pierces high-HP targets.',
    color: '#40a060',
    combatTag: 'ki',
  },
  gohan: {
    name: 'Scholar Burst',
    faction: 'dragonball',
    cost: 25,
    hp: 240,
    accuracy: 48,
    damage: 58,
    range: 28,
    meleeRange: 28,
    speed: 1.05,
    type: 'melee',
    morale: 30,
    experience: 14,
    ability: 'hidden_potential',
    abilityDesc: 'Hidden Potential — massive spike below 40% HP.',
    color: '#8040c0',
    combatTag: 'ki',
  },
  trunks: {
    name: 'Future Blade',
    faction: 'dragonball',
    cost: 25,
    hp: 210,
    accuracy: 54,
    damage: 56,
    range: 160,
    meleeRange: 26,
    speed: 1.08,
    type: 'ranged',
    projectile: 'bolt',
    morale: 28,
    experience: 13,
    ability: 'burning_attack',
    abilityDesc: 'Burning Attack — ranged burst finisher.',
    color: '#a040c0',
    combatTag: 'ki',
  },
  frieza: {
    name: 'Frost Tyrant',
    faction: 'dragonball',
    cost: 26,
    hp: 230,
    accuracy: 52,
    damage: 58,
    range: 155,
    meleeRange: 26,
    speed: 1.05,
    type: 'ranged',
    projectile: 'bolt',
    morale: 20,
    experience: 14,
    ability: 'death_beam',
    abilityDesc: 'Frost Lance — precision ranged execution.',
    color: '#c0c0c0',
    combatTag: 'ki',
  },
  cell: {
    name: 'Perfect Hybrid',
    faction: 'dragonball',
    cost: 26,
    hp: 260,
    accuracy: 50,
    damage: 60,
    range: 28,
    meleeRange: 28,
    speed: 1.08,
    type: 'melee',
    morale: 18,
    experience: 15,
    ability: 'perfect_form',
    abilityDesc: 'Perfect Form — heals on kill.',
    color: '#40c040',
    combatTag: 'ki',
  },
  beerus: {
    name: 'Cataclysm Lord',
    faction: 'dragonball',
    cost: 30,
    hp: 300,
    accuracy: 56,
    damage: 70,
    range: 32,
    meleeRange: 32,
    speed: 1.15,
    type: 'melee',
    morale: 24,
    experience: 16,
    ability: 'hakai',
    abilityDesc: 'Cataclysm — god-tier delete on wounded foes.',
    color: '#6040a0',
    combatTag: 'ki',
  },

  // Crimson Legions
  chapter_captain: {
    name: 'Legion Captain',
    faction: 'imperium',
    cost: 28,
    hp: 260,
    accuracy: 56,
    damage: 60,
    range: 175,
    meleeRange: 28,
    speed: 1.02,
    type: 'ranged',
    projectile: 'arrow',
    morale: 34,
    experience: 15,
    ability: 'bolter_discipline',
    abilityDesc: 'Volley Discipline — bonus damage with allied legionnaires nearby.',
    color: '#4060a0',
    combatTag: 'ranged',
  },
  chaplain: {
    name: 'War Chaplain',
    faction: 'imperium',
    cost: 25,
    hp: 220,
    accuracy: 52,
    damage: 58,
    range: 28,
    meleeRange: 28,
    speed: 1.0,
    type: 'melee',
    morale: 36,
    experience: 14,
    ability: 'litany_of_hate',
    abilityDesc: 'Litany of Hate — terrifies nearby foes on strike.',
    color: '#303848',
    combatTag: 'support',
  },
  librarian: {
    name: 'Rift Librarian',
    faction: 'imperium',
    cost: 25,
    hp: 190,
    accuracy: 54,
    damage: 56,
    range: 180,
    meleeRange: 26,
    speed: 1.0,
    type: 'ranged',
    projectile: 'bolt',
    morale: 28,
    experience: 14,
    ability: 'smite',
    abilityDesc: 'Smite — bonus damage vs arcane and undead casters.',
    color: '#5040a0',
    combatTag: 'ranged',
  },
  commissar: {
    name: 'Field Commissar',
    faction: 'imperium',
    cost: 23,
    hp: 200,
    accuracy: 50,
    damage: 48,
    range: 160,
    meleeRange: 26,
    speed: 1.05,
    type: 'ranged',
    projectile: 'arrow',
    morale: 40,
    experience: 13,
    ability: 'summary_execution',
    abilityDesc: 'Summary Execution — finishes routed, low-HP enemies.',
    color: '#802030',
    combatTag: 'support',
  },
  guardsman: {
    name: 'Line Guardsman',
    faction: 'imperium',
    cost: 20,
    hp: 165,
    accuracy: 46,
    damage: 38,
    range: 150,
    meleeRange: 24,
    speed: 0.98,
    type: 'ranged',
    projectile: 'arrow',
    morale: 22,
    experience: 9,
    ability: 'lasgun_volley',
    abilityDesc: 'Lasgun Volley — steady ranged line-holder with splash volleys.',
    color: '#506050',
    combatTag: 'ranged',
  },
  terminator: {
    name: 'Heavy Terminator',
    faction: 'imperium',
    cost: 30,
    hp: 340,
    accuracy: 44,
    damage: 64,
    range: 30,
    meleeRange: 30,
    speed: 0.82,
    type: 'melee',
    morale: 32,
    experience: 14,
    ability: 'storm_shield',
    abilityDesc: 'Storm Shield — damage reduction pulse when wounded.',
    color: '#384858',
    combatTag: 'melee',
  },
  dreadnought: {
    name: 'Iron Dreadnought',
    faction: 'imperium',
    cost: 33,
    hp: 380,
    accuracy: 42,
    damage: 68,
    range: 145,
    meleeRange: 30,
    speed: 0.75,
    type: 'ranged',
    projectile: 'bolt',
    morale: 30,
    experience: 13,
    ability: 'autocannon',
    abilityDesc: 'Autocannon — devastates siege engines and structures.',
    color: '#485868',
    combatTag: 'ranged',
  },

  // Crystal Vanguard (aether heroes — inspired by classic JRPG parties)
  soldier_of_light: {
    name: 'Soldier of Light',
    faction: 'crystal',
    cost: 26,
    hp: 250,
    accuracy: 54,
    damage: 62,
    range: 30,
    meleeRange: 30,
    speed: 1.08,
    type: 'melee',
    morale: 32,
    experience: 15,
    ability: 'cross_slash',
    abilityDesc: 'Cross Slash — finisher damage vs wounded foes.',
    color: '#5080c0',
    combatTag: 'melee',
  },
  black_mage: {
    name: 'Black Mage',
    faction: 'crystal',
    cost: 25,
    hp: 175,
    accuracy: 52,
    damage: 58,
    range: 185,
    meleeRange: 24,
    speed: 0.98,
    type: 'ranged',
    projectile: 'bolt',
    morale: 24,
    experience: 14,
    ability: 'firaga',
    abilityDesc: 'Firaga — burst fire when enemies cluster.',
    color: '#802040',
    combatTag: 'ranged',
  },
  white_mage: {
    name: 'White Mage',
    faction: 'crystal',
    cost: 22,
    hp: 180,
    accuracy: 48,
    damage: 42,
    range: 170,
    meleeRange: 24,
    speed: 1.0,
    type: 'ranged',
    projectile: 'bolt',
    morale: 36,
    experience: 13,
    ability: 'curaga',
    abilityDesc: 'Curaga — heals allies in combat aura.',
    color: '#f0f0f0',
    combatTag: 'support',
  },
  dragoon_knight: {
    name: 'Sky Lance',
    faction: 'crystal',
    cost: 25,
    hp: 210,
    accuracy: 54,
    damage: 60,
    range: 32,
    meleeRange: 32,
    speed: 1.18,
    type: 'cavalry',
    morale: 28,
    experience: 14,
    canHunt: true,
    ability: 'jump_attack',
    abilityDesc: 'Jump Attack — sky piercer bonus vs fast and flying foes.',
    color: '#4060a0',
    combatTag: 'melee',
  },
  summoner: {
    name: 'Aether Summoner',
    faction: 'crystal',
    cost: 24,
    hp: 195,
    accuracy: 50,
    damage: 54,
    range: 175,
    meleeRange: 26,
    speed: 1.0,
    type: 'ranged',
    projectile: 'bolt',
    morale: 30,
    experience: 14,
    ability: 'aeon_strike',
    abilityDesc: 'Aeon Strike — bonus damage vs elite enemies.',
    color: '#6040a0',
    combatTag: 'ranged',
  },
  limit_striker: {
    name: 'Limit Striker',
    faction: 'crystal',
    cost: 27,
    hp: 240,
    accuracy: 52,
    damage: 64,
    range: 28,
    meleeRange: 28,
    speed: 1.05,
    type: 'melee',
    morale: 26,
    experience: 15,
    ability: 'limit_break',
    abilityDesc: 'Limit Break — massive spike when wounded.',
    color: '#c04060',
    combatTag: 'melee',
  },
  crystal_sentinel: {
    name: 'Crystal Sentinel',
    faction: 'crystal',
    cost: 21,
    hp: 170,
    accuracy: 48,
    damage: 40,
    range: 155,
    meleeRange: 24,
    speed: 1.02,
    type: 'ranged',
    projectile: 'arrow',
    morale: 24,
    experience: 10,
    ability: 'aether_shot',
    abilityDesc: 'Aether Shot — reliable budget ranged DPS.',
    color: '#60a0c0',
    combatTag: 'ranged',
  },

  // Rift Cult
  chaos_champion: {
    name: 'Chaos Champion',
    faction: 'warp',
    cost: 27,
    hp: 270,
    accuracy: 50,
    damage: 64,
    range: 30,
    meleeRange: 30,
    speed: 1.02,
    type: 'melee',
    morale: 22,
    experience: 15,
    ability: 'warp_fury',
    abilityDesc: 'Warp Fury — damage surges when wounded.',
    color: '#802040',
    combatTag: 'melee',
  },
  plague_cultist: {
    name: 'Plague Cultist',
    faction: 'warp',
    cost: 22,
    hp: 200,
    accuracy: 44,
    damage: 46,
    range: 28,
    meleeRange: 28,
    speed: 0.92,
    type: 'melee',
    morale: 18,
    experience: 12,
    ability: 'festering_curse',
    abilityDesc: 'Festering Curse — slows and breaks enemy morale.',
    color: '#506030',
    combatTag: 'support',
  },
  warp_magus: {
    name: 'Warp Magus',
    faction: 'warp',
    cost: 25,
    hp: 185,
    accuracy: 52,
    damage: 56,
    range: 180,
    meleeRange: 26,
    speed: 1.0,
    type: 'ranged',
    projectile: 'bolt',
    morale: 20,
    experience: 14,
    ability: 'warp_bolt',
    abilityDesc: 'Warp Bolt — arcs to a second nearby foe.',
    color: '#6040c0',
    combatTag: 'ranged',
  },
  daemon_knight: {
    name: 'Daemon Knight',
    faction: 'warp',
    cost: 29,
    hp: 320,
    accuracy: 46,
    damage: 66,
    range: 32,
    meleeRange: 32,
    speed: 0.88,
    type: 'melee',
    morale: 24,
    experience: 14,
    ability: 'unholy_armor',
    abilityDesc: 'Unholy Armor — brief damage soak below 40% HP.',
    color: '#302030',
    combatTag: 'melee',
  },
  heretic_acolyte: {
    name: 'Heretic Acolyte',
    faction: 'warp',
    cost: 21,
    hp: 175,
    accuracy: 42,
    damage: 44,
    range: 26,
    meleeRange: 26,
    speed: 1.0,
    type: 'melee',
    morale: 16,
    experience: 10,
    ability: 'blood_pact',
    abilityDesc: 'Blood Pact — heals on kill.',
    color: '#704050',
    combatTag: 'melee',
  },
  possessed_marine: {
    name: 'Possessed Marine',
    faction: 'warp',
    cost: 26,
    hp: 230,
    accuracy: 48,
    damage: 58,
    range: 165,
    meleeRange: 28,
    speed: 0.95,
    type: 'ranged',
    projectile: 'bolt',
    morale: 18,
    experience: 13,
    ability: 'daemon_fire',
    abilityDesc: 'Daemon Fire — splash vs elite targets.',
    color: '#a04030',
    combatTag: 'ranged',
  },

  // Voicebound Pact — Wyrmcaller & Voice
  dragonborn: {
    name: 'Wyrmcaller',
    faction: 'tes',
    cost: 28,
    hp: 290,
    accuracy: 54,
    damage: 62,
    range: 30,
    meleeRange: 30,
    speed: 1.05,
    type: 'melee',
    morale: 34,
    experience: 16,
    ability: 'fus_ro_dah',
    abilityDesc: 'Voice Shout — force wave devastates clustered foes.',
    color: '#4068a0',
    combatTag: 'dragon',
  },
  greybeard_sage: {
    name: 'Mountain Hermit',
    faction: 'tes',
    cost: 22,
    hp: 200,
    accuracy: 48,
    damage: 42,
    range: 150,
    meleeRange: 24,
    speed: 0.92,
    type: 'ranged',
    projectile: 'bolt',
    morale: 32,
    experience: 14,
    ability: 'thuum_echo',
    abilityDesc: 'Voice Echo — empowers allies and weakens nearby foes on wave start.',
    color: '#708090',
    combatTag: 'support',
  },
  nord_huscarl: {
    name: 'Frost Huscarl',
    faction: 'tes',
    cost: 25,
    hp: 250,
    accuracy: 46,
    damage: 52,
    range: 28,
    meleeRange: 28,
    speed: 1.0,
    type: 'melee',
    morale: 28,
    experience: 12,
    ability: 'shield_wall',
    abilityDesc: 'Shield Wall — damage reduction when holding the line.',
    color: '#506878',
    combatTag: 'melee',
  },
  battlemage: {
    name: 'Storm Battlemage',
    faction: 'tes',
    cost: 25,
    hp: 185,
    accuracy: 52,
    damage: 56,
    range: 170,
    meleeRange: 26,
    speed: 1.0,
    type: 'ranged',
    projectile: 'bolt',
    morale: 24,
    experience: 13,
    ability: 'dragon_aspect',
    abilityDesc: 'Dragon Aspect — storm magic bonus vs elites and bosses.',
    color: '#6040a8',
    combatTag: 'ranged',
  },
  nightingale: {
    name: 'Shadow Nightingale',
    faction: 'tes',
    cost: 22,
    hp: 170,
    accuracy: 55,
    damage: 50,
    range: 26,
    meleeRange: 26,
    speed: 1.18,
    type: 'melee',
    morale: 22,
    experience: 12,
    ability: 'shadow_strike',
    abilityDesc: 'Shadow Strike — bonus crit damage vs wounded targets.',
    color: '#283848',
    combatTag: 'melee',
  },
  restoration_saint: {
    name: 'Restoration Saint',
    faction: 'tes',
    cost: 18,
    hp: 165,
    accuracy: 20,
    damage: 8,
    range: 110,
    meleeRange: 24,
    speed: 0.95,
    type: 'healer',
    healAmount: 24,
    morale: 30,
    experience: 11,
    ability: 'mara_blessing',
    abilityDesc: 'Mara Blessing — steady morale and healing aura.',
    color: '#a06080',
    combatTag: 'support',
  },
};

function getCrossoverDef(type) {
  return CrossoverDefs[type] || null;
}

function isCrossoverUnit(type) {
  return !!CrossoverDefs[type];
}

function isRosterUnit(type) {
  return (typeof isWweUnit === 'function' && isWweUnit(type)) || isCrossoverUnit(type);
}

function getCrossoverCombatTag(unit) {
  if (!unit) return 'melee';
  if (unit.combatTag) return unit.combatTag;
  const def =
    getCrossoverDef(unit.type) || (typeof getWweDef === 'function' ? getWweDef(unit.type) : null);
  if (def?.combatTag) return def.combatTag;
  if (def?.type === 'ranged') return 'ranged';
  if (unit.combatType === 'healer' || unit.type === 'healer') return 'support';
  if (
    unit.combatType === 'builder' ||
    unit.combatType === 'courier' ||
    unit.combatType === 'general'
  )
    return 'support';
  if (unit.combatType === 'ranged' || unit.projectile) return 'ranged';
  return 'melee';
}

function isFactionUnlocked(factionId) {
  const f = CrossoverFactions[factionId];
  if (!f || typeof MetaProgress === 'undefined') return false;
  const fn = MetaProgress[f.unlockKey];
  return typeof fn === 'function' ? fn() : false;
}

function getUnlockedFactions() {
  return Object.values(CrossoverFactions).filter((f) => isFactionUnlocked(f.id));
}

const CROSSOVER_FACTION_TAB_ORDER = [
  'ultimis',
  'primis',
  'halo',
  'gears',
  'lotr',
  'baki',
  'jojo',
  'fotns',
  'dragonball',
  'imperium',
  'crystal',
  'warp',
  'tes',
];

const CrossoverHub = (() => {
  let selectedId = null;
  let activeFaction = 'ultimis';

  function rosterForFaction(fid) {
    return Object.entries(CrossoverDefs).filter(([, d]) => d.faction === fid);
  }

  function getFeaturedOperativeId(fid, wave = 0) {
    const roster = rosterForFaction(fid);
    if (!roster.length) return null;
    const seed = (wave || 0) + [...fid].reduce((n, c) => n + c.charCodeAt(0), 0);
    return roster[seed % roster.length][0];
  }

  function sortUnlockedFactions(unlocked) {
    const order = CROSSOVER_FACTION_TAB_ORDER;
    return [...unlocked].sort((a, b) => {
      const ai = order.indexOf(a.id);
      const bi = order.indexOf(b.id);
      return (ai < 0 ? 99 : ai) - (bi < 0 ? 99 : bi);
    });
  }

  function hasFactionBuilding(fid, gs) {
    const f = CrossoverFactions[fid];
    if (!f) return false;
    return !!gs?.crossoverBuildings?.includes(f.building);
  }

  function renderRoster(gs) {
    const grid = document.getElementById('crossover-roster-grid');
    if (!grid) return;
    const unlocked = sortUnlockedFactions(getUnlockedFactions());
    if (unlocked.length && !unlocked.find((f) => f.id === activeFaction)) {
      activeFaction = unlocked[0].id;
    }

    const tabs = document.getElementById('crossover-faction-tabs');
    if (tabs) {
      tabs.innerHTML = unlocked
        .map((f) => {
          const count = rosterForFaction(f.id).length;
          return `
        <button class="crossover-tab ${f.id === activeFaction ? 'active' : ''}" data-faction="${f.id}" title="${count} operatives">${f.label} (${count})</button>
      `;
        })
        .join('');
      tabs.querySelectorAll('.crossover-tab').forEach((btn) => {
        btn.addEventListener('click', () => {
          activeFaction = btn.dataset.faction;
          selectedId = null;
          renderRoster(typeof Game !== 'undefined' ? Game.getState() : null);
          AudioEngine?.SFX?.click?.();
        });
      });
    }

    const entries = rosterForFaction(activeFaction);
    const featuredId = getFeaturedOperativeId(activeFaction, gs?.wave || 0);
    const sortedEntries = featuredId
      ? [...entries].sort((a, b) => (a[0] === featuredId ? -1 : b[0] === featuredId ? 1 : 0))
      : entries;
    const recruited = new Set(MetaProgress.getCrossoverRecruited?.() || []);
    grid.innerHTML =
      sortedEntries
        .map(([id, def]) => {
          const onField = gs?.crossoverOnField?.includes(id);
          const canAfford = (gs?.tactical ?? 0) >= def.cost;
          const hasBase = hasFactionBuilding(activeFaction, gs);
          const isFeatured = id === featuredId;
          return `
        <div class="wwe-card crossover-card ${selectedId === id ? 'selected' : ''} ${isFeatured ? 'crossover-featured' : ''} ${!canAfford || !hasBase || onField ? 'cant-afford' : ''}" data-crossover="${id}">
          ${isFeatured ? '<div class="crossover-featured-badge">Featured</div>' : ''}
          <div class="wwe-card-name" style="color:${def.color}">${def.name}</div>
          <div class="wwe-card-cost">${def.cost} TP</div>
          <div class="wwe-card-stats">HP ${def.hp} · DMG ${def.damage} · ${def.type}${def.jojoPart ? ` · Pt.${def.jojoPart}` : ''}</div>
          <div class="wwe-card-ability">${def.abilityDesc}</div>
          ${recruited.has(id) ? '<div class="wwe-recruited">★ Signed</div>' : ''}
          ${onField ? '<div class="wwe-on-field">ON FIELD</div>' : ''}
          ${!hasBase ? '<div class="crossover-need-base">Need barracks on field</div>' : ''}
        </div>
      `;
        })
        .join('') || '<p class="crossover-empty">No operatives available for this faction yet.</p>';

    grid.querySelectorAll('.crossover-card').forEach((card) => {
      card.addEventListener('click', () => {
        selectedId = card.dataset.crossover;
        renderRoster(typeof Game !== 'undefined' ? Game.getState() : null);
        AudioEngine?.SFX?.click?.();
      });
    });

    const detail = document.getElementById('crossover-selected-detail');
    const prof =
      typeof FactionDepth !== 'undefined' ? FactionDepth.getProfile(activeFaction) : null;
    const mastery =
      typeof FactionDepth !== 'undefined' ? FactionDepth.getMasteryPoints(activeFaction) : 0;
    const title =
      typeof FactionDepth !== 'undefined' ? FactionDepth.getMasteryTitle(activeFaction) : null;
    const seasonals = typeof FactionDepth !== 'undefined' ? FactionDepth.getSeasonalEvents() : [];
    const seasonal =
      seasonals.find((e) => e.factions?.includes(activeFaction)) || seasonals[0] || null;
    const synHint =
      typeof FactionDepth !== 'undefined'
        ? FactionDepth.SYNERGIES.filter((s) => s.factions.includes(activeFaction))
            .slice(0, 2)
            .map((s) => s.name)
            .join(', ')
        : '';
    const recruitBtn = document.getElementById('crossover-recruit-btn');
    if (recruitBtn) {
      if (!selectedId) {
        recruitBtn.disabled = true;
      } else {
        const selOnField = gs?.crossoverOnField?.includes(selectedId);
        const selDef = CrossoverDefs[selectedId];
        const selAfford = selDef && (gs?.tactical ?? 0) >= selDef.cost;
        const selBase = hasFactionBuilding(activeFaction, gs);
        recruitBtn.disabled = !!(selOnField || !selAfford || !selBase);
      }
    }

    if (detail && selectedId && CrossoverDefs[selectedId]) {
      const d = CrossoverDefs[selectedId];
      const costNote =
        typeof FactionDepth !== 'undefined' && gs
          ? ` (≈${Math.ceil(d.cost * FactionDepth.getDeployCostMult(activeFaction, gs.wave || 0))} TP)`
          : '';
      const fieldNote = gs?.crossoverOnField?.includes(selectedId)
        ? '<br><em>Already deployed — wait until they fall to recruit again.</em>'
        : '';
      detail.innerHTML = `<strong>${d.name}</strong> — ${d.abilityDesc}<br>Cost: ${d.cost} TP${costNote} · Tag: ${d.combatTag}${fieldNote}`;
    } else if (detail) {
      if (prof) {
        detail.innerHTML = `<strong>${prof.label}</strong>${title ? ` · <em>${title}</em>` : ''}<br>
          Mastery: ${mastery} pts · ${prof.identity}<br>
          <span class="crossover-weakness">Weakness: ${prof.weakness}</span><br>
          ${synHint ? `Synergies: ${synHint}` : ''}${seasonal?.factions?.includes(activeFaction) ? `<br>🎉 ${seasonal.name}` : ''}`;
      } else {
        detail.textContent = unlocked.length
          ? 'Select a evolved operative below.'
          : 'Unlock a evolved roster first — then build its barracks and recruit operatives here.';
      }
    }
  }

  function togglePanel(factionId) {
    const panel = document.getElementById('crossover-screen');
    if (!panel) return;
    if (factionId) activeFaction = factionId;
    const open = panel.classList.toggle('active');
    if (open) renderRoster(typeof Game !== 'undefined' ? Game.getState() : null);
  }

  function getSelected() {
    return selectedId;
  }
  function getActiveFaction() {
    return activeFaction;
  }

  function init() {
    document.getElementById('crossover-hub-open')?.addEventListener('click', () => {
      AudioEngine?.SFX?.click?.();
      const unlocked =
        (typeof MetaProgress !== 'undefined' && MetaProgress.isAnyCrossoverUnlocked?.()) ||
        (typeof Research !== 'undefined' &&
          Object.keys(CrossoverFactions || {}).some((f) => Research.isFactionUnlocked?.(f, {})));
      if (!unlocked) {
        // Prefer in-game toast if HUD is live.
        if (typeof UI !== 'undefined' && UI.updateHUD) {
          const box = document.getElementById('message-box');
          if (box) {
            box.textContent =
              'No evolved factions unlocked — Iron Creed unlocks or Research → Evolved Allies.';
            box.classList.add('show');
            setTimeout(() => box.classList.remove('show'), 2800);
          }
        }
        return;
      }
      togglePanel();
    });
    document.getElementById('crossover-close')?.addEventListener('click', () => {
      document.getElementById('crossover-screen')?.classList.remove('active');
    });
    document.getElementById('crossover-recruit-btn')?.addEventListener('click', () => {
      if (!selectedId) return;
      const gs = typeof Game !== 'undefined' ? Game.getState() : null;
      if (gs?.crossoverOnField?.includes(selectedId)) return;
      if (typeof Game !== 'undefined') Game.recruitCrossoverOperative(selectedId);
      renderRoster(Game.getState());
      UI.updateHUD(true);
    });
    document.getElementById('crossover-build-btn')?.addEventListener('click', () => {
      const f = CrossoverFactions[activeFaction];
      if (f && typeof Game !== 'undefined') Game.selectBuild(f.building);
      togglePanel();
      UI.updateHUD(true);
    });
  }

  return {
    init,
    togglePanel,
    renderRoster,
    getSelected,
    getActiveFaction,
    rosterForFaction,
    getFeaturedOperativeId,
    sortUnlockedFactions,
  };
})();
